version: "3"

services:

  backend:
    build: ./docker
    ports:
      - "5000:5000"
    env_file:
      - .env

  frontend:
    image: node:18
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: npm run dev
    ports:
      - "5173:5173"