version: "3"

services:

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env

  frontend:
    image: node:22
    working_dir: /app
    volumes:
      - ./frontend/quick-response-tool:/app
    command: sh -c "npm install && npm run dev -- --host"
    ports:
      - "5173:5173"