name: CI

on:
  pull_request:
    branches: [main]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - name: Install Backend
        run: |
          cd backend
          npm install

      - name: Install Frontend
        run: |
          cd frontend
          npm install

      - name: Lint
        run: |
          cd backend
          npm run lint || true

      - name: Build Frontend
        run: |
          cd frontend
          npm run build