name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Backend Dependencies
        run: |
          cd backend
          npm install

      - name: Install Frontend Dependencies
        run: |
          cd frontend/quick-response-tool
          npm install

      - name: Lint Backend
        run: |
          cd backend
          npm run lint || true

      - name: Build Frontend
        run: |
          cd frontend/quick-response-tool
          npm run build


  deploy-backend:
    if: github.event_name == 'push'
    needs: build
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/sales-insight-backend:latest ./backend

      # Push Docker Image
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/sales-insight-backend:latest

      # Trigger Render Deployment
      - name: Trigger Render Deployment
        run: |
          curl ${{ secrets.RENDER_DEPLOY_HOOK }}

      # Trigger Vercel Deployment
      - name: Trigger Vercel Deployment
        run: |
          curl -X POST ${{ secrets.VERCEL_DEPLOY_HOOK }}